#!/usr/bin/bash

docker run -ti --rm --net local_stack -v ./:/aws \
    -e AWS_REGION=us-east-1 \
    -e AWS_ACCESS_KEY_ID=test \
    -e AWS_SECRET_ACCESS_KEY=test \
    -e AWS_ENDPOINT_URL=http://localstack:4566 \
    --entrypoint /bin/sh \
    d191680ecbe8
